tasks:
  - init: |
      pip install --upgrade pip
      pip install -r requirements.txt || true

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.black-formatter
    - eamodio.gitlens
